In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
overview = pd.read_csv('characters_overview.csv')

In [3]:
overview.isna().sum()

character                              0
Ant-Man                                0
Avengers: Age of Ultron                0
Avengers: Endgame                      0
Avengers: Infinity War                 0
Black Panther                          0
Captain America: Civil War             0
Captain America: The First Avenger     0
Captain America: The Winter Soldier    0
Captain Marvel                         0
Guardians of the Galaxy Vol. 2         0
Iron Man                               0
Iron Man 2                             0
Iron Man 3                             0
Spider-Man: Homecoming                 0
The Avengers                           0
Thor                                   0
Thor: Ragnarok                         0
Thor: The Dark World                   0
total lines                            0
total words                            0
movie appearances                      0
avg words per line                     0
avg lines per movie                    0
dtype: int64

In [4]:
overview.describe()

,Ant-Man,Avengers: Age of Ultron,Avengers: Endgame,Avengers: Infinity War,Black Panther,Captain America: Civil War,Captain America: The First Avenger,Captain America: The Winter Soldier,Captain Marvel,Guardians of the Galaxy Vol. 2,...,Spider-Man: Homecoming,The Avengers,Thor,Thor: Ragnarok,Thor: The Dark World,total lines,total words,movie appearances,avg words per line,avg lines per movie
count,652.000000,652.000000,652.000000,652.000000,652.000000,652.000000,652.000000,652.000000,652.000000,652.000000,...,652.000000,652.000000,652.000000,652.000000,652.000000,652.000000,652.000000,652.000000,652.000000,652.000000
mean,1.243865,1.472393,1.648773,1.427914,1.062883,1.417178,1.030675,1.219325,1.056748,1.222393,...,1.946319,1.452454,1.283742,1.207055,1.009202,24.116564,265.570552,1.374233,10.243865,9.763804
std,11.810604,11.031202,10.097267,8.424747,7.833367,10.542615,8.793884,10.708083,10.376396,10.845285,...,17.914420,10.929851,10.198830,12.675257,8.252723,100.968073,1155.743539,1.168380,15.399754,19.432092
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,7.000000,1.000000,4.000000,1.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,22.000000,1.000000,7.000000,2.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,9.000000,90.250000,1.000000,12.000000,8.000000
max,222.000000,173.000000,137.000000,119.000000,125.000000,165.000000,186.000000,218.000000,211.000000,183.000000,...,402.000000,152.000000,166.000000,289.000000,133.000000,1788.000000,22590.000000,11.000000,235.000000,198.000000

In [11]:
pd.set_option("display.max_columns", None)
overview.loc[overview['avg words per line']==overview['avg words per line'].max()]

,character,Ant-Man,Avengers: Age of Ultron,Avengers: Endgame,Avengers: Infinity War,Black Panther,Captain America: Civil War,Captain America: The First Avenger,Captain America: The Winter Soldier,Captain Marvel,Guardians of the Galaxy Vol. 2,Iron Man,Iron Man 2,Iron Man 3,Spider-Man: Homecoming,The Avengers,Thor,Thor: Ragnarok,Thor: The Dark World,total lines,total words,movie appearances,avg words per line,avg lines per movie
435,TV REPORTER’S VOICE,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,235,1,235,1